sudo: required
services:
  - docker

before_install: 
  - docker build -t murtazadocker/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true USERNAME/react-test npm test

after_success: 
  - docker build -t murtazadocker/multi-client ./client
  - docker build -t murtazadocker/multi-nginx ./nginx
  - docker build -t murtazadocker/multi-server ./server
  - docker build -t murtazadocker/multi-worker ./worker