sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t murtaza/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true USERNAME/react-test npm test

after_success: 
  - docker build -t murtaza/multi-client ./client
  - docker build -t murtaza/multi-nginx ./nginx
  - docker build -t murtaza/multi-server ./server
  - docker build -t murtaza/multi-worker ./worker
# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to doker hub 
  - docker push murtaza/multi-client
  - docker push murtaza/multi-nginx
  - docker push murtaza/multi-server
  - docker push murtaza/multi-worker

